DATA_TYPE_SCHEMA = {
    "demo1": {
        "$id": "TODO_1",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "description": "Dummy data type 1",
        "type": "object",
        "required": ["id", "content"],
        "properties": {
            "id": {
                "type": "string",
                "search": {
                    "operations": ["eq", "lt", "le", "gt", "ge", "co"],
                    "canNegate": True,
                    "required": False,
                    "type": "unlimited",  # single / unlimited
                    "order": 0
                }
            },
            "content": {
                "type": "string",
                "search": {
                    "operations": ["eq", "lt", "le", "gt", "ge", "co"],
                    "canNegate": True,
                    "required": False,
                    "type": "unlimited",  # single / unlimited
                    "order": 1
                }
            }
        }
    },
    "demo2": {
        "$id": "TODO_2",
        "$schema": "http://json-schema.org/draft-07/schema#",
        "description": "Dummy data type 2",
        "type": "object",
        "required": ["id", "content"],
        "properties": {
            "id": {
                "type": "string",
                "search": {
                    "operations": ["eq", "lt", "le", "gt", "ge", "co"],
                    "canNegate": True,
                    "required": False,
                    "type": "unlimited",  # single / unlimited
                    "order": 0
                }
            },
            "content": {
                "type": "string",
                "search": {
                    "operations": ["eq", "lt", "le", "gt", "ge", "co"],
                    "canNegate": True,
                    "required": False,
                    "type": "unlimited",  # single / unlimited
                    "order": 1
                }
            }
        }
    }
}

TABLE_METADATA_SCHEMA = {
    "$id": "TODO",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "CHORD demo data type metadata schema",
    "type": "object",
    "properties": {
        "created": {
            "type": "string",
            "chord_autogenerated": True  # TODO: Extend schema
        },
        "updated": {
            "type": "string",
            "chord_autogenerated": True  # TODO: Extend schema
        }
    }
}
